### ISSUE TITLE
Tweak.js Examples 1st link (tweak.js) is not working

### ISSUE THREAD

**Issue by hwclass** [tweak-js/website#1]
Hi all,

In the first section of the Examples page writing "tweakjs.com ..." under the Examples title and content, if you click the link, it won't go to the github page.

If you click as I mentioned above in the first, it goes to : "https://github.com/tweak-js/tweak-web" and showing Github 404 page.

It could be updated. I have created a branh to make a pull request but have no permission to push it.

Thanks.

**Comment by blake-newman** [comment]
Hello,  Thanks for the information. 

I have stopped maintaining this,  I will be splitting the core modules into micro libraries in the near future.  

I recommend you looking at https://github.com/vuejs/vue it was my original albeit slightly different ambitions.
